export const prompts2 = [
  { text: "What's the most embarrassing thing you've done while trying to impress someone?", category: "Dating" },
  { text: "If you could only communicate through song lyrics for a day, what would be the hardest part?", category: "Music" },
  { text: "What's your most ridiculous conspiracy theory that you low-key believe?", category: "Opinions" },
  { text: "If you were a condiment, which one would you be and why?", category: "Food & Drink" },
  { text: "What's the worst pickup line you've ever used or heard?", category: "Dating" },
  { text: "If you could have any mythical creature as a sidekick, what would it be?", category: "Fantasy" },
  { text: "What's your most embarrassing autocorrect moment?", category: "Technology" },
  { text: "If you had to survive a zombie apocalypse with only the items in your room, how screwed are you?", category: "Survival" },
  { text: "What's the weirdest thing you've ever Googled at 3 AM?", category: "Technology" },
  { text: "If you could be a character in any sitcom, which one would you choose?", category: "Entertainment" },
  { text: "What's your most embarrassing moment at work or school?", category: "Work" },
  { text: "If you had to choose between having fingers for toes or toes for fingers, which would you pick?", category: "Hypotheticals" },
  { text: "What's the dumbest thing you've ever done on a dare?", category: "Adventures" },
  { text: "If you could only use one emoji for the rest of your life, which one would it be?", category: "Technology" },
  { text: "What's your most embarrassing Spotify playlist?", category: "Music" },
  { text: "If you were a breakfast food, what would you be?", category: "Food & Drink" },
  { text: "What's the worst haircut decision you've ever made?", category: "Fashion" },
  { text: "If you could have any superpower but only while you're sleeping, what would it be?", category: "Hypotheticals" },
  { text: "What's your most cringe-worthy pickup line attempt?", category: "Dating" },
  { text: "If you had to live in a house shaped like any object, what would it be?", category: "Random" },
  { text: "What's the most embarrassing thing you've ever posted on social media?", category: "Social Media" },
  { text: "If you could be best friends with any celebrity, who would it be?", category: "Entertainment" },
  { text: "What's your weirdest shower thought?", category: "Personal" },
  { text: "If you had to choose between never being able to use GPS again or never being able to use autocorrect again, which would you choose?", category: "Technology" },
  { text: "What's the most ridiculous thing you've ever impulse bought?", category: "Shopping" },
  { text: "If you were a type of pasta, which one would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing karaoke performance?", category: "Entertainment" },
  { text: "If you could live in any fictional universe, which one would you choose?", category: "Fantasy" },
  { text: "What's the weirdest thing you've ever done to avoid someone?", category: "Social" },
  { text: "If you had to choose between never eating dessert again or never eating breakfast again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most embarrassing drunk text?", category: "Party" },
  { text: "If you could be a professional in any weird sport, what would it be?", category: "Sports" },
  { text: "What's the most awkward encounter you've had with a stranger?", category: "Social" },
  { text: "If you were a type of cheese, which one would you be?", category: "Food & Drink" },
  { text: "What's your most irrational superstition?", category: "Personal" },
  { text: "If you could only watch one genre of movies for the rest of your life, what would it be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever argued about?", category: "Relationships" },
  { text: "If you had to choose a new first name, what would it be?", category: "Personal" },
  { text: "What's your most embarrassing moment in front of a crush?", category: "Dating" },
  { text: "If you could be any kitchen utensil, which one would you be?", category: "Random" },
  { text: "What's the worst advice you've ever given someone?", category: "Life" },
  { text: "If you had to live without hot water or without air conditioning, which would you choose?", category: "Life" },
  { text: "What's your most ridiculous childhood belief?", category: "Childhood" },
  { text: "If you were a type of tree, what tree would you be?", category: "Nature" },
  { text: "What's the most embarrassing thing you've done while half asleep?", category: "Personal" },
  { text: "If you could have any animal's ability, what would it be?", category: "Animals" },
  { text: "What's your weirdest comfort food?", category: "Food & Drink" },
  { text: "If you had to choose between living without the internet or living without AC/heating, which would you choose?", category: "Technology" },
  { text: "What's the most awkward compliment you've ever received?", category: "Social" },
  { text: "If you were a type of shoe, what would you be?", category: "Fashion" },
  { text: "What's your most embarrassing gym moment?", category: "Fitness" },
  { text: "If you could only eat food of one color for the rest of your life, what color would you choose?", category: "Food & Drink" },
  { text: "What's the dumbest thing you've ever done for a photo?", category: "Social Media" },
  { text: "If you were a household item, what would you be?", category: "Random" },
  { text: "What's your most embarrassing moment during a video call?", category: "Work" },
  { text: "If you could have any job for just one hour, what would it be?", category: "Career" },
  { text: "What's the weirdest thing you've ever collected?", category: "Hobbies" },
  { text: "If you had to choose between never using emojis again or never using GIFs again, which would you choose?", category: "Technology" },
  { text: "What's your most irrational reason for disliking someone?", category: "Personal" },
  { text: "If you were a type of coffee drink, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done in front of your boss?", category: "Work" },
  { text: "If you could be famous on TikTok for one specific thing, what would it be?", category: "Social Media" },
  { text: "What's your weirdest late-night snack combination?", category: "Food & Drink" },
  { text: "If you had to choose between never watching Netflix again or never listening to music again, which would you choose?", category: "Entertainment" },
  { text: "What's the most ridiculous thing you've ever done to win a bet?", category: "Adventures" },
  { text: "If you were a type of candy, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a party?", category: "Party" },
  { text: "If you could have any cartoon character's life, whose would it be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done when you thought nobody was watching?", category: "Personal" },
  { text: "If you had to choose between never eating fruit again or never eating vegetables again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment in a restaurant?", category: "Food & Drink" },
  { text: "If you were a type of cookie, what would you be?", category: "Food & Drink" },
  { text: "What's the dumbest thing you've ever done while trying to multitask?", category: "Life" },
  { text: "If you could only wear one color for the rest of your life, what would it be?", category: "Fashion" },
  { text: "What's your most embarrassing moment while traveling?", category: "Travel" },
  { text: "If you were a type of soup, what would you be?", category: "Food & Drink" },
  { text: "What's the weirdest thing you've ever done to make someone laugh?", category: "Social" },
  { text: "If you had to choose between never eating meat again or never eating carbs again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous fear that you've never told anyone about?", category: "Personal" },
  { text: "If you were a type of cake, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be cool?", category: "Personal" },
  { text: "If you could have any superpower but it only works on Tuesdays, what would it be?", category: "Hypotheticals" },
  { text: "What's your weirdest pre-sleep ritual?", category: "Personal" },
  { text: "If you had to choose between never using your phone again or never using your computer again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever said during a job interview?", category: "Work" },
  { text: "If you were a type of sandwich, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at the gym?", category: "Fitness" },
  { text: "If you could only listen to one song for the rest of your life, what would it be?", category: "Music" },
  { text: "What's the dumbest thing you've ever done because you were bored?", category: "Personal" },
  { text: "If you were a type of fruit, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment during online shopping?", category: "Shopping" },
  { text: "If you could have any fictional character's wardrobe, whose would it be?", category: "Fashion" },
  { text: "What's the weirdest thing you've ever done to procrastinate?", category: "Life" },
  { text: "If you had to choose between never eating sweet food again or never eating salty food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous talent that's completely useless?", category: "Personal" },
  { text: "If you were a type of beverage, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to take a selfie?", category: "Social Media" },
  { text: "If you could be a professional video game player for any game, which game would it be?", category: "Gaming" },
  { text: "What's your weirdest guilty pleasure?", category: "Personal" },
];
