export const prompts5 = [
  { text: "If you were a type of ranch dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a coffee shop?", category: "Food & Drink" },
  { text: "If you could have any chef's cooking skills, whose would you want?", category: "Food & Drink" },
  { text: "What's the weirdest thing you've ever done to make friends?", category: "Social" },
  { text: "If you had to choose between never eating sandwiches again or never eating burgers again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not cleaning?", category: "Life" },
  { text: "If you were a type of Caesar dressing, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be cool online?", category: "Social Media" },
  { text: "If you could be a character in any adventure movie, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest way of dealing with stress?", category: "Personal" },
  { text: "If you had to choose between never using Chrome again or never using Safari again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a retirement party?", category: "Social" },
  { text: "If you were a type of blue cheese dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while babysitting?", category: "Life" },
  { text: "If you could have any entrepreneur's mindset, whose would you want?", category: "Career" },
  { text: "What's the dumbest thing you've ever done while jealous?", category: "Emotions" },
  { text: "If you were a type of Italian dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a bar?", category: "Party" },
  { text: "If you could be a character in any dystopian novel, who would you be?", category: "Books" },
  { text: "What's the weirdest thing you've ever done to get someone's attention?", category: "Social" },
  { text: "If you had to choose between never eating wraps again or never eating burritos again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not answering the phone?", category: "Technology" },
  { text: "If you were a type of balsamic vinaigrette, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be mysterious online?", category: "Social Media" },
  { text: "If you could have any scientist's intellect, whose would you want?", category: "Science" },
  { text: "What's your weirdest way of celebrating?", category: "Personal" },
  { text: "If you had to choose between never using Windows again or never using Mac again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at an engagement party?", category: "Social" },
  { text: "If you were a type of thousand island dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while pet sitting?", category: "Animals" },
  { text: "If you could be a character in any coming-of-age story, who would you be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while proud?", category: "Emotions" },
  { text: "If you were a type of French dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a club?", category: "Party" },
  { text: "If you could have any inventor's creativity, whose would you want?", category: "Innovation" },
  { text: "What's the weirdest thing you've ever done to avoid responsibility?", category: "Life" },
  { text: "If you had to choose between never eating quesadillas again or never eating nachos again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not doing laundry?", category: "Life" },
  { text: "If you were a type of honey mustard, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to go viral?", category: "Social Media" },
  { text: "If you could be a character in any biographical movie, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest way of showing affection?", category: "Relationships" },
  { text: "If you had to choose between never using Android again or never using iOS again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at an anniversary party?", category: "Social" },
  { text: "If you were a type of chipotle mayo, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while house sitting?", category: "Life" },
  { text: "If you could have any explorer's courage, whose would you want?", category: "Adventures" },
  { text: "What's the dumbest thing you've ever done while embarrassed?", category: "Emotions" },
  { text: "If you were a type of garlic aioli, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a rave?", category: "Party" },
  { text: "If you could be a character in any war movie, who would you be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to prove a point?", category: "Personal" },
  { text: "If you had to choose between never eating fries again or never eating onion rings again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not replying to messages?", category: "Technology" },
  { text: "If you were a type of sriracha mayo, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to get followers?", category: "Social Media" },
  { text: "If you could have any leader's charisma, whose would you want?", category: "Career" },
  { text: "What's your weirdest way of relaxing?", category: "Personal" },
  { text: "If you had to choose between never using Firefox again or never using Edge again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a holiday party?", category: "Social" },
  { text: "If you were a type of wasabi mayo, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while dog walking?", category: "Animals" },
  { text: "If you could be a character in any sports movie, who would you be?", category: "Sports" },
  { text: "What's the dumbest thing you've ever done while guilty?", category: "Emotions" },
  { text: "If you were a type of truffle aioli, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a festival?", category: "Entertainment" },
  { text: "If you could have any artist's vision, whose would you want?", category: "Art" },
  { text: "What's the weirdest thing you've ever done to fit in?", category: "Social" },
  { text: "If you had to choose between never eating wings again or never eating nuggets again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not going to the gym?", category: "Fitness" },
  { text: "If you were a type of lemon aioli, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to get likes?", category: "Social Media" },
  { text: "If you could be a character in any heist movie, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest way of motivating yourself?", category: "Personal" },
  { text: "If you had to choose between never using Photoshop again or never using Illustrator again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a potluck?", category: "Social" },
  { text: "If you were a type of herb aioli, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while plant sitting?", category: "Life" },
  { text: "If you could have any philosopher's wisdom, whose would you want?", category: "Philosophy" },
  { text: "What's the dumbest thing you've ever done while ashamed?", category: "Emotions" },
  { text: "If you were a type of curry mayo, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a tailgate?", category: "Sports" },
  { text: "If you could be a character in any spy movie, who would you be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to stand out?", category: "Personal" },
  { text: "If you had to choose between never eating mozzarella sticks again or never eating jalapeño poppers again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for being messy?", category: "Life" },
  { text: "If you were a type of lime aioli, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to trend?", category: "Social Media" },
  { text: "If you could have any architect's design sense, whose would you want?", category: "Art" },
  { text: "What's your weirdest nighttime routine?", category: "Personal" },
  { text: "If you had to choose between never using Word again or never using Google Docs again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a picnic?", category: "Social" },
  { text: "If you were a type of cilantro lime dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while car sitting?", category: "Life" },
  { text: "If you could be a character in any zombie movie, who would you be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while shocked?", category: "Emotions" },
  { text: "If you were a type of ginger dressing, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a game night?", category: "Social" },
  { text: "If you could have any fashion designer's style, whose would you want?", category: "Fashion" },
  { text: "What's the weirdest thing you've ever done to blend in?", category: "Social" },
];
