export const prompts7 = [
  { text: "What's your most controversial opinion about breakfast cereal?", category: "Food & Drink" },
  { text: "If you could have any artist's creative process, whose would you want?", category: "Art" },
  { text: "What's the dumbest thing you've ever done because you were distracted?", category: "Personal" },
  { text: "If you were a type of ocean creature, what would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment at a sporting event?", category: "Sports" },
  { text: "If you could master any type of photography, which style?", category: "Art" },
  { text: "What's the weirdest thing you've ever done to stay awake?", category: "Personal" },
  { text: "If you had to give up either coffee or alcohol forever, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous Amazon purchase?", category: "Shopping" },
  { text: "If you were a type of constellation, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a baby shower?", category: "Social" },
  { text: "If you could have any writer's way with words, whose would you want?", category: "Books" },
  { text: "What's your weirdest guilty pleasure song?", category: "Music" },
  { text: "If you had to eat only one type of Asian cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be adventurous?", category: "Adventures" },
  { text: "If you were a type of ecosystem, what would you be?", category: "Nature" },
  { text: "What's your most controversial take on dating apps?", category: "Dating" },
  { text: "If you could have any speedrunner's skills, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were cold?", category: "Personal" },
  { text: "If you were a type of bird, what bird would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment while on a video date?", category: "Dating" },
  { text: "If you could instantly learn any design software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to make friends?", category: "Social" },
  { text: "If you had to choose between never eating Italian food again or never eating Mexican food again, which?", category: "Food & Drink" },
  { text: "What's your most ridiculous monthly expense?", category: "Life" },
  { text: "If you were a type of galaxy, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a work party?", category: "Work" },
  { text: "If you could have any musician's stage presence, whose would you want?", category: "Music" },
  { text: "What's your weirdest comfort food?", category: "Food & Drink" },
  { text: "If you had to eat only one type of European cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be cultured?", category: "Culture" },
  { text: "If you were a type of mountain range, what would you be?", category: "Nature" },
  { text: "What's your most controversial opinion about streaming services?", category: "Entertainment" },
  { text: "If you could have any pro player's game sense, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were hot?", category: "Personal" },
  { text: "If you were a type of insect, what would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment while trying to network?", category: "Work" },
  { text: "If you could master any video editing software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to avoid work?", category: "Work" },
  { text: "If you had to give up either pizza or burgers forever, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous hobby?", category: "Hobbies" },
  { text: "If you were a type of nebula, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a bachelor/bachelorette party?", category: "Party" },
  { text: "If you could have any comedian's timing, whose would you want?", category: "Entertainment" },
  { text: "What's your weirdest food aversion?", category: "Food & Drink" },
  { text: "If you had to eat only one type of Latin American cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be sophisticated?", category: "Personal" },
  { text: "If you were a type of desert, what would you be?", category: "Nature" },
  { text: "What's your most controversial take on work-life balance?", category: "Work" },
  { text: "If you could have any streamer's personality, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were stressed?", category: "Personal" },
  { text: "If you were a type of reptile, what would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment during a team building exercise?", category: "Work" },
  { text: "If you could instantly master any 3D software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to procrastinate?", category: "Life" },
  { text: "If you had to choose between never eating Chinese food again or never eating Thai food again, which?", category: "Food & Drink" },
  { text: "What's your most ridiculous collection?", category: "Hobbies" },
  { text: "If you were a type of black hole, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a housewarming?", category: "Social" },
  { text: "If you could have any actor's range, whose would you want?", category: "Entertainment" },
  { text: "What's your weirdest food ritual?", category: "Food & Drink" },
  { text: "If you had to eat only one type of Middle Eastern cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be artistic?", category: "Art" },
  { text: "If you were a type of rainforest, what would you be?", category: "Nature" },
  { text: "What's your most controversial opinion about remote work?", category: "Work" },
  { text: "If you could have any content creator's consistency, whose would you want?", category: "Social Media" },
  { text: "What's the dumbest thing you've ever done because you were excited?", category: "Emotions" },
  { text: "If you were a type of amphibian, what would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment during a performance review?", category: "Work" },
  { text: "If you could instantly learn any animation software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to save time?", category: "Life" },
  { text: "If you had to give up either sushi or tacos forever, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous New Year's resolution?", category: "Life" },
  { text: "If you were a type of comet, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a potluck dinner?", category: "Social" },
  { text: "If you could have any director's vision, whose would you want?", category: "Entertainment" },
  { text: "What's your weirdest food preference?", category: "Food & Drink" },
  { text: "If you had to eat only one type of African cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be intellectual?", category: "Personal" },
  { text: "If you were a type of tundra, what would you be?", category: "Nature" },
  { text: "What's your most controversial take on social norms?", category: "Society" },
  { text: "If you could have any modder's technical skills, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were bored?", category: "Personal" },
  { text: "If you were a type of fish, what would you be?", category: "Animals" },
  { text: "What's your most embarrassing moment during a client meeting?", category: "Work" },
  { text: "If you could master any audio editing software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to save money?", category: "Life" },
  { text: "If you had to choose between never eating Indian food again or never eating Japanese food again, which?", category: "Food & Drink" },
  { text: "What's your most ridiculous fear from adulthood?", category: "Personal" },
  { text: "If you were a type of asteroid, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a dinner party?", category: "Social" },
  { text: "If you could have any producer's ear for music, whose would you want?", category: "Music" },
  { text: "What's your weirdest eating schedule?", category: "Food & Drink" },
  { text: "If you had to eat only one type of Caribbean cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be trendy?", category: "Fashion" },
  { text: "If you were a type of savanna, what would you be?", category: "Nature" },
  { text: "What's your most controversial opinion about modern technology?", category: "Technology" },
  { text: "If you could have any developer's coding skills, whose would you want?", category: "Technology" },
  { text: "What's the dumbest thing you've ever done because you were lazy?", category: "Personal" },
];
