export const prompts1 = [
  { text: "If you were a vegetable, what vegetable would you be and why?", category: "Icebreakers" },
  { text: "What's your most embarrassing childhood memory?", category: "Icebreakers" },
  { text: "If you could have dinner with any fictional character, who would it be?", category: "Hypotheticals" },
  { text: "What's the weirdest food combination you secretly enjoy?", category: "Food & Drink" },
  { text: "If you could only eat one food for the rest of your life, what would it be?", category: "Food & Drink" },
  { text: "What's your go-to karaoke song?", category: "Entertainment" },
  { text: "If you had to live in a TV show, which one would you choose?", category: "Entertainment" },
  { text: "What's the most useless talent you have?", category: "Personal" },
  { text: "If you could swap lives with anyone for a day, who would it be?", category: "Hypotheticals" },
  { text: "What's your most irrational fear?", category: "Personal" },
  { text: "If animals could talk, which one would be the rudest?", category: "Animals" },
  { text: "What's the worst haircut you've ever had?", category: "Personal" },
  { text: "If you could be famous for something ridiculous, what would it be?", category: "Hypotheticals" },
  { text: "What's your guilty pleasure TV show?", category: "Entertainment" },
  { text: "If you had to wear one outfit for the rest of your life, what would it be?", category: "Fashion" },
  { text: "What's the strangest dream you've ever had?", category: "Personal" },
  { text: "If you could have any superpower but it had to be completely useless, what would it be?", category: "Hypotheticals" },
  { text: "What's the most ridiculous thing you've ever bought?", category: "Shopping" },
  { text: "If you were a ghost, who would you haunt and why?", category: "Hypotheticals" },
  { text: "What's your most unpopular opinion?", category: "Opinions" },
  { text: "If you could instantly become an expert in something, what would it be?", category: "Skills" },
  { text: "What's the weirdest compliment you've ever received?", category: "Personal" },
  { text: "If you had to delete all but 3 apps from your phone, which ones would you keep?", category: "Technology" },
  { text: "What's your most embarrassing autocorrect fail?", category: "Technology" },
  { text: "If you could time travel but only to embarrassing moments in history, where would you go?", category: "History" },
  { text: "What's the worst advice you've ever received?", category: "Life" },
  { text: "If you were a kitchen appliance, which one would you be?", category: "Random" },
  { text: "What's your signature dance move?", category: "Entertainment" },
  { text: "If you could rename yourself, what name would you choose?", category: "Personal" },
  { text: "What's the most awkward situation you've ever been in?", category: "Personal" },
  { text: "If you had to fight 100 duck-sized horses or 1 horse-sized duck, which would you choose?", category: "Hypotheticals" },
  { text: "What's your weirdest habit?", category: "Personal" },
  { text: "If you could live in any era, when would it be?", category: "History" },
  { text: "What's the most spontaneous thing you've ever done?", category: "Adventures" },
  { text: "If you were a flavor of ice cream, what would you be?", category: "Food & Drink" },
  { text: "What's your most controversial hot take?", category: "Opinions" },
  { text: "If you could be any age forever, what age would you choose?", category: "Life" },
  { text: "What's the dumbest way you've ever injured yourself?", category: "Personal" },
  { text: "If you had to live without one of your five senses, which one would you give up?", category: "Hypotheticals" },
  { text: "What's your most embarrassing moment in public?", category: "Personal" },
  { text: "If you could have any animal as a pet (real or mythical), what would it be?", category: "Animals" },
  { text: "What's the worst movie you've ever seen?", category: "Entertainment" },
  { text: "If you could master any instrument instantly, which one would it be?", category: "Music" },
  { text: "What's your go-to excuse for getting out of plans?", category: "Social" },
  { text: "If you were stranded on a desert island, what three items would you bring?", category: "Survival" },
  { text: "What's the most cringe-worthy thing you did as a teenager?", category: "Personal" },
  { text: "If you could read minds but only when people are thinking about food, would you want that power?", category: "Hypotheticals" },
  { text: "What's your most bizarre pet peeve?", category: "Personal" },
  { text: "If you had to eat at only one restaurant for the rest of your life, which would it be?", category: "Food & Drink" },
  { text: "What's the weirdest thing you believed as a child?", category: "Childhood" },
  { text: "If you could be a professional athlete in any sport, which sport would you choose?", category: "Sports" },
  { text: "What's your most embarrassing drunk story?", category: "Party" },
  { text: "If you could eliminate one thing from daily life, what would it be?", category: "Life" },
  { text: "What's the worst date you've ever been on?", category: "Dating" },
  { text: "If you had to live in a video game, which one would you choose?", category: "Gaming" },
  { text: "What's your secret talent that nobody knows about?", category: "Personal" },
  { text: "If you could speak to one species of animal, which would it be?", category: "Animals" },
  { text: "What's the most ridiculous argument you've ever had?", category: "Relationships" },
  { text: "If you could have free unlimited supply of one thing for life, what would it be?", category: "Hypotheticals" },
  { text: "What's your most irrational dealbreaker in a relationship?", category: "Dating" },
  { text: "If you were a pizza topping, what would you be?", category: "Food & Drink" },
  { text: "What's the worst gift you've ever received?", category: "Gifts" },
  { text: "If you could be invisible for a day, what would you do?", category: "Hypotheticals" },
  { text: "What's your most embarrassing fashion phase?", category: "Fashion" },
  { text: "If you had to choose between never using social media again or never watching TV/movies again, which would you choose?", category: "Technology" },
  { text: "What's the strangest thing you've ever eaten?", category: "Food & Drink" },
  { text: "If you could instantly learn any language, which would it be?", category: "Languages" },
  { text: "What's your most ridiculous fear from childhood that you still have?", category: "Personal" },
  { text: "If you were a type of weather, what would you be?", category: "Random" },
  { text: "What's the most embarrassing thing in your search history?", category: "Technology" },
  { text: "If you could have dinner with any three people (dead or alive), who would they be?", category: "Hypotheticals" },
  { text: "What's your weirdest flex?", category: "Personal" },
  { text: "If you had to give up cheese or chocolate forever, which would you choose?", category: "Food & Drink" },
  { text: "What's the most awkward text you've ever sent to the wrong person?", category: "Technology" },
  { text: "If you could be reincarnated as any object, what would you be?", category: "Hypotheticals" },
  { text: "What's your most embarrassing celebrity crush?", category: "Entertainment" },
  { text: "If you had to wear a warning label, what would it say?", category: "Personal" },
  { text: "What's the dumbest thing you've ever cried about?", category: "Emotions" },
  { text: "If you could switch bodies with someone for a week, who would it be?", category: "Hypotheticals" },
  { text: "What's your most controversial food opinion?", category: "Food & Drink" },
  { text: "If you were a meme, which one would you be?", category: "Internet" },
  { text: "What's the worst lie you've ever told?", category: "Personal" },
  { text: "If you could have any job in the world for just one day, what would it be?", category: "Career" },
  { text: "What's your most embarrassing Google search?", category: "Technology" },
  { text: "If you had to live without music or without movies for the rest of your life, which would you choose?", category: "Entertainment" },
  { text: "What's the weirdest thing you do when you're alone?", category: "Personal" },
  { text: "If you could bring back any fashion trend, what would it be?", category: "Fashion" },
  { text: "What's your most irrational pet peeve?", category: "Personal" },
  { text: "If you were a candy, what candy would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing your parents have caught you doing?", category: "Family" },
  { text: "If you could have any fictional character as your best friend, who would it be?", category: "Entertainment" },
  { text: "What's your go-to dance move when nobody's watching?", category: "Personal" },
  { text: "If you had to choose between never eating pizza again or never eating tacos again, which would you choose?", category: "Food & Drink" },
  { text: "What's the most ridiculous thing you've done for love?", category: "Romance" },
  { text: "If you could be a fly on the wall anywhere, where would it be?", category: "Hypotheticals" },
  { text: "What's your most embarrassing wardrobe malfunction?", category: "Fashion" },
  { text: "If you had to pick a theme song for your life, what would it be?", category: "Music" },
  { text: "What's the weirdest nickname you've ever had?", category: "Personal" },
  { text: "If you could eliminate one chore from your life forever, what would it be?", category: "Life" },
];
