export const prompts4 = [
  { text: "What's your most embarrassing moment while singing in public?", category: "Entertainment" },
  { text: "If you could be a character in any sci-fi universe, who would you be?", category: "Sci-Fi" },
  { text: "What's the dumbest thing you've ever done while caffeinated?", category: "Food & Drink" },
  { text: "If you were a type of chocolate, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at the airport?", category: "Travel" },
  { text: "If you could have any animator's skills, whose would you want?", category: "Art" },
  { text: "What's the weirdest thing you've ever done to stay awake?", category: "Personal" },
  { text: "If you had to choose between never eating homemade food again or never eating restaurant food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous phobia?", category: "Personal" },
  { text: "If you were a type of jelly, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be mysterious?", category: "Personal" },
  { text: "If you could be a character in any horror movie, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest study habit?", category: "Education" },
  { text: "If you had to choose between never using WhatsApp again or never using Telegram again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a sleepover?", category: "Social" },
  { text: "If you were a type of mustard, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while playing an instrument?", category: "Music" },
  { text: "If you could have any director's vision, whose would you want?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while excited?", category: "Personal" },
  { text: "If you were a type of ketchup, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a theme park?", category: "Entertainment" },
  { text: "If you could be a character in any musical, who would you be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to impress a teacher?", category: "Education" },
  { text: "If you had to choose between never eating breakfast food again or never eating dinner food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous habit that annoys others?", category: "Personal" },
  { text: "If you were a type of mayo, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be funny?", category: "Social" },
  { text: "If you could have any photographer's eye, whose would you want?", category: "Art" },
  { text: "What's your weirdest bedtime routine?", category: "Personal" },
  { text: "If you had to choose between never using Discord again or never using Slack again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a birthday party?", category: "Social" },
  { text: "If you were a type of relish, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while acting?", category: "Entertainment" },
  { text: "If you could be a character in any Western, who would you be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while angry?", category: "Emotions" },
  { text: "If you were a type of hot sauce, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a pool party?", category: "Social" },
  { text: "If you could have any writer's storytelling ability, whose would you want?", category: "Books" },
  { text: "What's the weirdest thing you've ever done to avoid doing homework?", category: "Education" },
  { text: "If you had to choose between never eating lunch again or never eating snacks again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous pet peeve about technology?", category: "Technology" },
  { text: "If you were a type of BBQ sauce, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be sophisticated?", category: "Personal" },
  { text: "If you could be a character in any crime drama, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest cleaning habit?", category: "Personal" },
  { text: "If you had to choose between never using Zoom again or never using Google Meet again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a graduation?", category: "Education" },
  { text: "If you were a type of soy sauce, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while doing karaoke?", category: "Entertainment" },
  { text: "If you could have any comedian's timing, whose would you want?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while nervous?", category: "Personal" },
  { text: "If you were a type of teriyaki sauce, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a museum?", category: "Culture" },
  { text: "If you could be a character in any period drama, who would you be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to stay cool in summer?", category: "Life" },
  { text: "If you had to choose between never eating appetizers again or never eating entrees again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous reason for calling in sick?", category: "Work" },
  { text: "If you were a type of fish sauce, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be athletic?", category: "Sports" },
  { text: "If you could have any musician's talent, whose would you want?", category: "Music" },
  { text: "What's your weirdest driving habit?", category: "Life" },
  { text: "If you had to choose between never using email again or never using text messages again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a baby shower?", category: "Social" },
  { text: "If you were a type of pesto, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while presenting?", category: "Work" },
  { text: "If you could be a character in any action movie, who would you be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while happy?", category: "Emotions" },
  { text: "If you were a type of aioli, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a library?", category: "Education" },
  { text: "If you could have any dancer's moves, whose would you want?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to stay warm in winter?", category: "Life" },
  { text: "If you had to choose between never eating side dishes again or never eating main courses again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for not exercising?", category: "Fitness" },
  { text: "If you were a type of chutney, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be smart?", category: "Personal" },
  { text: "If you could be a character in any rom-com, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest eating habit?", category: "Food & Drink" },
  { text: "If you had to choose between never using voice calls again or never using video calls again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a bridal shower?", category: "Social" },
  { text: "If you were a type of salsa, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while teaching?", category: "Education" },
  { text: "If you could have any magician's skills, whose would you want?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while sad?", category: "Emotions" },
  { text: "If you were a type of guacamole, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a bookstore?", category: "Books" },
  { text: "If you could be a character in any thriller, who would you be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to fall asleep?", category: "Personal" },
  { text: "If you had to choose between never eating soups again or never eating salads again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for being on your phone?", category: "Technology" },
  { text: "If you were a type of hummus, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be brave?", category: "Personal" },
  { text: "If you could have any athlete's dedication, whose would you want?", category: "Sports" },
  { text: "What's your weirdest shopping habit?", category: "Shopping" },
  { text: "If you had to choose between never using Google again or never using Bing again, which would you choose?", category: "Technology" },
  { text: "What's the most awkward thing you've ever done at a housewarming party?", category: "Social" },
  { text: "If you were a type of tzatziki, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while volunteering?", category: "Life" },
  { text: "If you could be a character in any mystery novel, who would you be?", category: "Books" },
  { text: "What's the dumbest thing you've ever done while confused?", category: "Personal" },
];
