export const prompts6 = [
  { text: "If you could only communicate using movie quotes for a week, which movie would you choose?", category: "Entertainment" },
  { text: "What's the most ridiculous thing you've ever Googled?", category: "Technology" },
  { text: "If you had to get a tattoo right now, what would you get?", category: "Personal" },
  { text: "What's your most embarrassing autocorrect story?", category: "Technology" },
  { text: "If you could be a professional at any Olympic sport, which one?", category: "Sports" },
  { text: "What's the weirdest compliment you've ever given someone?", category: "Social" },
  { text: "If you had to live in a different decade, which would you choose?", category: "History" },
  { text: "What's your most controversial take on breakfast foods?", category: "Food & Drink" },
  { text: "If you could instantly master any dance style, which one?", category: "Entertainment" },
  { text: "What's the dumbest way you've ever tried to impress someone?", category: "Dating" },
  { text: "If you were a type of weather phenomenon, what would you be?", category: "Random" },
  { text: "What's your most embarrassing moment on public transportation?", category: "Travel" },
  { text: "If you could have any celebrity's closet, whose would it be?", category: "Fashion" },
  { text: "What's the weirdest food combination you've actually tried?", category: "Food & Drink" },
  { text: "If you had to give up one social media platform forever, which one?", category: "Social Media" },
  { text: "What's your most irrational reason for not liking someone?", category: "Personal" },
  { text: "If you could be fluent in any programming language, which one?", category: "Technology" },
  { text: "What's the most embarrassing thing you've done while working from home?", category: "Work" },
  { text: "If you were a type of natural disaster, what would you be?", category: "Random" },
  { text: "What's your go-to lie when you don't want to hang out?", category: "Social" },
  { text: "If you could have any superpower but only on weekends, what would it be?", category: "Hypotheticals" },
  { text: "What's the weirdest thing you've ever bought online at 2 AM?", category: "Shopping" },
  { text: "If you had to compete in a reality TV show, which one?", category: "Entertainment" },
  { text: "What's your most embarrassing moment in a Zoom meeting?", category: "Work" },
  { text: "If you were a type of cloud, what cloud would you be?", category: "Random" },
  { text: "What's the dumbest thing you've ever done for a dare?", category: "Adventures" },
  { text: "If you could only listen to one podcast for the rest of your life, which one?", category: "Entertainment" },
  { text: "What's your most ridiculous fear that you've never admitted?", category: "Personal" },
  { text: "If you were a type of extreme sport, what would you be?", category: "Sports" },
  { text: "What's the most awkward thing you've ever said on a first date?", category: "Dating" },
  { text: "If you could have any fictional character's job, whose would it be?", category: "Entertainment" },
  { text: "What's your weirdest midnight snack?", category: "Food & Drink" },
  { text: "If you had to wear one brand for the rest of your life, which one?", category: "Fashion" },
  { text: "What's the most embarrassing thing you've posted on social media?", category: "Social Media" },
  { text: "If you were a type of natural landmark, what would you be?", category: "Travel" },
  { text: "What's your most controversial opinion about pizza?", category: "Food & Drink" },
  { text: "If you could have any YouTuber's subscriber count, whose would you want?", category: "Social Media" },
  { text: "What's the dumbest thing you've ever done while drunk?", category: "Party" },
  { text: "If you were a type of gemstone, what would you be?", category: "Random" },
  { text: "What's your most embarrassing gym fail?", category: "Fitness" },
  { text: "If you could master any extreme hobby, which one?", category: "Hobbies" },
  { text: "What's the weirdest thing you've ever done to avoid small talk?", category: "Social" },
  { text: "If you had to live in any video game world, which one?", category: "Gaming" },
  { text: "What's your most ridiculous online shopping regret?", category: "Shopping" },
  { text: "If you were a type of precious metal, what would you be?", category: "Random" },
  { text: "What's the most awkward thing you've witnessed at a wedding?", category: "Social" },
  { text: "If you could have any TikToker's viral moment, whose would it be?", category: "Social Media" },
  { text: "What's your weirdest habit when you're home alone?", category: "Personal" },
  { text: "If you had to survive on only one cuisine forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to flirt?", category: "Dating" },
  { text: "If you were a type of architectural style, what would you be?", category: "Art" },
  { text: "What's your most controversial take on coffee?", category: "Food & Drink" },
  { text: "If you could have any streamer's gaming setup, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because of peer pressure?", category: "Social" },
  { text: "If you were a type of fabric, what would you be?", category: "Fashion" },
  { text: "What's your most embarrassing moment at a job interview?", category: "Work" },
  { text: "If you could instantly learn any craft or skill, which one?", category: "Skills" },
  { text: "What's the weirdest thing you've ever done to win an argument?", category: "Relationships" },
  { text: "If you had to live without one of your favorite apps, which one could you give up?", category: "Technology" },
  { text: "What's your most ridiculous impulse purchase?", category: "Shopping" },
  { text: "If you were a type of musical genre, what would you be?", category: "Music" },
  { text: "What's the most awkward thing you've done at a family reunion?", category: "Family" },
  { text: "If you could have any influencer's brand partnerships, whose would you want?", category: "Social Media" },
  { text: "What's your weirdest pre-game ritual?", category: "Sports" },
  { text: "If you had to eat at only one fast food chain forever, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be healthy?", category: "Health" },
  { text: "If you were a type of art movement, what would you be?", category: "Art" },
  { text: "What's your most controversial opinion about social media?", category: "Social Media" },
  { text: "If you could have any gamer's skill level, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were tired?", category: "Personal" },
  { text: "If you were a type of flower, what would you be?", category: "Nature" },
  { text: "What's your most embarrassing moment during a presentation?", category: "Work" },
  { text: "If you could master any form of martial arts, which one?", category: "Sports" },
  { text: "What's the weirdest thing you've ever done to get someone's attention?", category: "Dating" },
  { text: "If you had to give up either Netflix or Spotify, which would you choose?", category: "Entertainment" },
  { text: "What's your most ridiculous late-night purchase?", category: "Shopping" },
  { text: "If you were a type of season, what would you be?", category: "Random" },
  { text: "What's the most awkward thing you've done at a concert?", category: "Entertainment" },
  { text: "If you could have any content creator's editing skills, whose would you want?", category: "Social Media" },
  { text: "What's your weirdest superstition?", category: "Personal" },
  { text: "If you had to live on only one type of cuisine's street food, which one?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be spontaneous?", category: "Adventures" },
  { text: "If you were a type of architectural wonder, what would you be?", category: "Travel" },
  { text: "What's your most controversial take on relationships?", category: "Dating" },
  { text: "If you could have any esports player's reflexes, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done because you were hungry?", category: "Food & Drink" },
  { text: "If you were a type of tree, what tree would you be and why?", category: "Nature" },
  { text: "What's your most embarrassing moment while traveling abroad?", category: "Travel" },
  { text: "If you could instantly become an expert in any software, which one?", category: "Technology" },
  { text: "What's the weirdest thing you've ever done to avoid someone?", category: "Social" },
  { text: "If you had to choose between never watching movies again or never reading books again, which?", category: "Entertainment" },
  { text: "What's your most ridiculous subscription service?", category: "Technology" },
  { text: "If you were a type of planet, what would you be?", category: "Science" },
  { text: "What's the most awkward thing you've done at a networking event?", category: "Work" },
  { text: "If you could have any photographer's eye for composition, whose would you want?", category: "Art" },
  { text: "What's your weirdest comfort movie?", category: "Entertainment" },
  { text: "If you had to eat only one restaurant's menu forever, which restaurant?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be eco-friendly?", category: "Environment" },
  { text: "If you were a type of biome, what would you be?", category: "Nature" },
];
