export const prompts3 = [
  { text: "If you had to live in a world where everyone could read your thoughts, what would be your biggest concern?", category: "Hypotheticals" },
  { text: "What's the most embarrassing song on your liked songs playlist?", category: "Music" },
  { text: "If you were a type of bread, what would you be?", category: "Food & Drink" },
  { text: "What's your most awkward encounter with a celebrity or someone famous?", category: "Entertainment" },
  { text: "If you could only use one social media platform for the rest of your life, which would it be?", category: "Social Media" },
  { text: "What's the dumbest thing you've ever done to impress your friends?", category: "Social" },
  { text: "If you were a type of dessert, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment during a first date?", category: "Dating" },
  { text: "If you could have any YouTuber's life for a day, whose would it be?", category: "Social Media" },
  { text: "What's the weirdest thing you've ever done when you couldn't sleep?", category: "Personal" },
  { text: "If you had to choose between never eating hot food again or never eating cold food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous online purchase you regret?", category: "Shopping" },
  { text: "If you were a type of nut, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done in front of your in-laws?", category: "Family" },
  { text: "If you could master any TikTok trend instantly, which one would it be?", category: "Social Media" },
  { text: "What's your weirdest morning routine habit?", category: "Personal" },
  { text: "If you had to choose between never watching YouTube again or never using Instagram again, which would you choose?", category: "Social Media" },
  { text: "What's the most awkward thing you've ever said to a stranger?", category: "Social" },
  { text: "If you were a type of spice, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while working from home?", category: "Work" },
  { text: "If you could be a professional eater of any food, what food would it be?", category: "Food & Drink" },
  { text: "What's the dumbest thing you've ever done while distracted by your phone?", category: "Technology" },
  { text: "If you were a type of herb, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a family gathering?", category: "Family" },
  { text: "If you could have any influencer's brand deals, whose would you want?", category: "Social Media" },
  { text: "What's the weirdest thing you've ever done to avoid awkward small talk?", category: "Social" },
  { text: "If you had to choose between never eating fried food again or never eating baked food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous excuse for being late?", category: "Life" },
  { text: "If you were a type of sauce, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while drunk texting?", category: "Party" },
  { text: "If you could be on any reality TV show, which one would it be?", category: "Entertainment" },
  { text: "What's your weirdest food craving?", category: "Food & Drink" },
  { text: "If you had to choose between never using Spotify again or never using YouTube Music again, which would you choose?", category: "Music" },
  { text: "What's the most awkward thing you've ever witnessed?", category: "Social" },
  { text: "If you were a type of grain, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while exercising?", category: "Fitness" },
  { text: "If you could have any podcast host's job, whose would it be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever believed from the internet?", category: "Technology" },
  { text: "If you were a type of oil, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at the doctor's office?", category: "Health" },
  { text: "If you could only watch one streaming service for the rest of your life, which would it be?", category: "Entertainment" },
  { text: "What's the weirdest thing you've ever done to get out of a conversation?", category: "Social" },
  { text: "If you had to choose between never eating crunchy food again or never eating soft food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous New Year's resolution that you never kept?", category: "Life" },
  { text: "If you were a type of milk, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to flirt?", category: "Dating" },
  { text: "If you could be a character in any anime, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest stress relief method?", category: "Personal" },
  { text: "If you had to choose between never using Twitter again or never using Reddit again, which would you choose?", category: "Social Media" },
  { text: "What's the most awkward thing you've ever done at a wedding?", category: "Social" },
  { text: "If you were a type of flour, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while public speaking?", category: "Work" },
  { text: "If you could have any streamer's setup, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done while cooking?", category: "Food & Drink" },
  { text: "If you were a type of sugar, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a concert?", category: "Entertainment" },
  { text: "If you could be a character in any book series, which one would you choose?", category: "Books" },
  { text: "What's the weirdest thing you've ever done to make a good first impression?", category: "Social" },
  { text: "If you had to choose between never eating spicy food again or never eating bland food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous childhood dream job?", category: "Childhood" },
  { text: "If you were a type of vinegar, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be romantic?", category: "Romance" },
  { text: "If you could have any esports player's skills, whose would you want?", category: "Gaming" },
  { text: "What's your weirdest productivity hack?", category: "Work" },
  { text: "If you had to choose between never using TikTok again or never using Snapchat again, which would you choose?", category: "Social Media" },
  { text: "What's the most awkward thing you've ever done at a funeral?", category: "Social" },
  { text: "If you were a type of salt, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while playing sports?", category: "Sports" },
  { text: "If you could be a character in any comic book, who would you be?", category: "Entertainment" },
  { text: "What's the dumbest thing you've ever done while tired?", category: "Personal" },
  { text: "If you were a type of butter, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at the beach?", category: "Travel" },
  { text: "If you could have any content creator's audience, whose would you want?", category: "Social Media" },
  { text: "What's the weirdest thing you've ever done to win an argument?", category: "Relationships" },
  { text: "If you had to choose between never eating organic food again or never eating processed food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous fashion trend you participated in?", category: "Fashion" },
  { text: "If you were a type of cream, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be healthy?", category: "Health" },
  { text: "If you could be a character in any Marvel or DC universe, who would you be?", category: "Entertainment" },
  { text: "What's your weirdest way of organizing things?", category: "Personal" },
  { text: "If you had to choose between never using Facebook again or never using LinkedIn again, which would you choose?", category: "Social Media" },
  { text: "What's the most awkward thing you've ever done at a job interview?", category: "Work" },
  { text: "If you were a type of yogurt, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment while dancing?", category: "Entertainment" },
  { text: "If you could have any gaming YouTuber's setup, whose would you want?", category: "Gaming" },
  { text: "What's the dumbest thing you've ever done while hangry?", category: "Food & Drink" },
  { text: "If you were a type of honey, what would you be?", category: "Food & Drink" },
  { text: "What's your most embarrassing moment at a sporting event?", category: "Sports" },
  { text: "If you could be a character in any fantasy world, which one would you choose?", category: "Fantasy" },
  { text: "What's the weirdest thing you've ever done to save money?", category: "Life" },
  { text: "If you had to choose between never eating leftovers again or never eating fresh food again, which would you choose?", category: "Food & Drink" },
  { text: "What's your most ridiculous bucket list item?", category: "Life" },
  { text: "If you were a type of jam, what would you be?", category: "Food & Drink" },
  { text: "What's the most embarrassing thing you've done while trying to be eco-friendly?", category: "Environment" },
  { text: "If you could have any voice actor's voice, whose would you want?", category: "Entertainment" },
  { text: "What's your weirdest way of remembering things?", category: "Personal" },
  { text: "If you had to choose between never using Pinterest again or never using Tumblr again, which would you choose?", category: "Social Media" },
  { text: "What's the most awkward thing you've ever done while meeting someone's parents?", category: "Dating" },
  { text: "If you were a type of syrup, what would you be?", category: "Food & Drink" },
];
