export const prompts8 = [
  { text: "My toxic trait is ______", category: "Personal" },
  { text: "My villain origin story was when ______", category: "Personal" },
  { text: "Nothing hits harder than ______", category: "Humor" },
  { text: "I have strong opinions about ______ and I will not be taking questions", category: "Opinions" },
  { text: "I peaked when ______", category: "Personal" },
  { text: "My sleep schedule was destroyed by ______", category: "Personal" },
  { text: "The most 'main character' moment of my life was ______", category: "Personal" },
  { text: "I tried to act completely normal but then ______ happened", category: "Humor" },
  { text: "My brain at 3 AM: ______", category: "Humor" },
  { text: "I would trade my entire personality for the ability to ______", category: "Hypotheticals" },
  { text: "I once convinced myself that ______ was a personality trait", category: "Personal" },
  { text: "The reason I can't have nice things is ______", category: "Humor" },
  { text: "My biggest red flag is ______", category: "Dating" },
  { text: "______ lives rent free in my head", category: "Personal" },
  { text: "I became a completely different person the day I discovered ______", category: "Personal" },
  { text: "I spent way too long learning ______ and I use it exactly never", category: "Skills" },
  { text: "I would go to war for ______", category: "Humor" },
  { text: "The audacity of ______ is truly unmatched", category: "Humor" },
  { text: "My love language is ______", category: "Dating" },
  { text: "I don't have a type, I have a pattern, and that pattern is ______", category: "Dating" },
];
